In [35]:
#Normalisoidaan ja siivotaan laadullista dataa
import pandas as pd
import numpy as np

LISTINGSFILE = "http://data.insideairbnb.com/italy/lombardy/milan/2021-12-15/data/listings.csv.gz"

cols = ['host_response_time']
df = pd.read_csv(LISTINGSFILE, usecols=cols, compression='infer')

df['host_response_time'] = df['host_response_time'].fillna('N/A')
dummies = pd.get_dummies(df.host_response_time)
df = pd.concat((df.drop(['host_response_time'], axis = 1), dummies.astype(int)), axis = 1)
df.describe()

xMean = np.mean(df, axis=0)
xDev = np.std(df, axis=0)
xNorm = (df - xMean) / xDev
xNorm

,N/A,a few days or more,within a day,within a few hours,within an hour
0,1.271685,-0.194368,-0.333179,-0.369995,-0.751917
1,1.271685,-0.194368,-0.333179,-0.369995,-0.751917
2,-0.786358,5.144873,-0.333179,-0.369995,-0.751917
3,1.271685,-0.194368,-0.333179,-0.369995,-0.751917
4,1.271685,-0.194368,-0.333179,-0.369995,-0.751917
...,...,...,...,...,...
16779,-0.786358,-0.194368,-0.333179,-0.369995,1.329934
16780,-0.786358,-0.194368,-0.333179,-0.369995,1.329934
16781,-0.786358,-0.194368,-0.333179,2.702739,-0.751917
16782,-0.786358,-0.194368,-0.333179,-0.369995,1.329934
16783,-0.786358,-0.194368,-0.333179,-0.369995,1.329934